  -- Necessaria a criação de sequence para Funcao de montagem do ID
  CREATE SEQUENCE  "SYSTEM"."SEQUENCE_USUARIO_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
  
  -- Instruções SQL de criação da Função CRIA_ID_COMPLEX
  CREATE OR REPLACE FUNCTION "SYSTEM"."CRIA_ID_COMPLEX" (
    EMAIL_FUNC      IN VARCHAR2, 
    NOME_FUNC       IN VARCHAR2,
    SEXO_FUNC       IN VARCHAR2,
    NASCIMENTO_FUNC IN VARCHAR2,
    SENHA_FUNC      IN VARCHAR2
) RETURN VARCHAR2 AS 
BEGIN
    DECLARE
    ID VARCHAR2(32);
    SEQ VARCHAR2(32);
    TOKEN VARCHAR(6) := 'sBBHcK';
    
    BEGIN
        SELECT SEQUENCE_USUARIO_ID.NEXTVAL INTO SEQ FROM USUARIO WHERE ROWNUM <= 1;
        ID := rawtohex(dbms_obfuscation_toolkit.md5(input => utl_raw.cast_to_raw( SEQ || CURRENT_DATE || TOKEN )));
        INSERT INTO USUARIO (ID, EMAIL, NOME, SEXO, NASCIMENTO, SENHA)
        VALUES(ID, EMAIL_FUNC, NOME_FUNC, SEXO_FUNC, TO_DATE(NASCIMENTO_FUNC, 'YYYY-MM-DD'), SENHA_FUNC);
        RETURN ID;
    END;
    
END CRIA_ID_COMPLEX;