CREATE TABLE USUARIO 
(
  ID VARCHAR2(255) NOT NULL 
, EMAIL VARCHAR2(255) 
, NOME VARCHAR2(80) 
, SEXO VARCHAR2(1) 
, NASCIMENTO DATE 
, SENHA VARCHAR2(32) 
, CONSTRAINT USUARIO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN USUARIO.ID IS 'Id do usuário';

COMMENT ON COLUMN USUARIO.EMAIL IS 'Email/login do usuário';

COMMENT ON COLUMN USUARIO.NOME IS 'Nome do usuário';

COMMENT ON COLUMN USUARIO.SEXO IS 'Sexo do usuário – M ou F';

COMMENT ON COLUMN USUARIO.NASCIMENTO IS 'Data de nascimento do usuário (dd/mm/yyyy)';

COMMENT ON COLUMN USUARIO.SENHA IS 'Senha do usuário criptografada';

--EVITA CADASTRO DE E-MAILS REPETIDOS
ALTER TABLE USUARIO ADD CONSTRAINT UQEMAIL UNIQUE (EMAIL);