  CREATE TABLE "ANDERSON"."USUARIO" 
   (	"ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"NOME" VARCHAR2(80 BYTE), 
	"SEXO" VARCHAR2(1 BYTE), 
	"NASCIMENTO" DATE, 
	"SENHA" VARCHAR2(32 BYTE), 
	 CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ANDERSON"."USUARIO"."ID" IS 'Id do usuário';
   COMMENT ON COLUMN "ANDERSON"."USUARIO"."EMAIL" IS 'Email/login do usuário';
   COMMENT ON COLUMN "ANDERSON"."USUARIO"."NOME" IS 'Nome do usuário';
   COMMENT ON COLUMN "ANDERSON"."USUARIO"."SEXO" IS 'Sexo do usuário – M ou F';
   COMMENT ON COLUMN "ANDERSON"."USUARIO"."NASCIMENTO" IS 'Data de nascimento do usuário (dd/mm/yyyy)';
   COMMENT ON COLUMN "ANDERSON"."USUARIO"."SENHA" IS 'Senha do usuário criptografada';